name: Inputcooldown
version: 1.1.0
description: inputcooldown plugin
author: Hraponssi
main: net.hraponssi.inputcooldown.main.Main
depend: [Vault]
api-version: 1.13
commands:
   ic:
      description: manage input cooldowns
      usage: /<command> <subcommand>
      permission: ic.user
   inputcooldown:
      description: manage input cooldowns
      usage: /<command> <subcommand>
      permission: ic.user
permissions:
  ic.*:
    description: Gives access to all commands for managing input cooldowns
    default: false
    children:
      ic.user: true
      ic.admin: true
  ic.user:
    description: Allows you to receive alerts
    default: true
  ic.admin:
    description: Allows you to manage the config
    default: false