#InputCooldown Config

#Minimum plot access level for setting input cooldowns
#Options: Owner, Trusted, Member
minimumAccess: Owner

maxTime: 3600
minTime: 3
maxPlotCooldowns: -1

adminModeJoinMsg: true
disableAdminOnQuit: false

cmdUnset: true