name: Inputcooldown
version: 1.1.4
description: inputcooldown plugin
author: Hraponssi
main: net.hraponssi.inputcooldown.main.Main
softdepend: [Multiverse-Core, PlotSquared]
api-version: 1.17
commands:
   ic:
      description: manage input cooldowns
      usage: /<command> <subcommand>
      permission: ic.user
   inputcooldown:
      description: manage input cooldowns
      usage: /<command> <subcommand>
      permission: ic.user
permissions:
  ic.*:
    description: Gives access to all commands for managing input cooldowns
    default: op
    children:
      ic.user: true
      ic.admin: true
      ic.reload: true
  ic.user:
    description: Allows you to receive alerts
    default: true
  ic.admin:
    description: Allows you to control all cooldowns
    default: op
  ic.reload:
    description: Allows you to reload the config
    default: op
